name: pandoc-converter build

on:
  pull_request: {}
  push: # Do not rely on `push` for PR CI - see https://github.com/guardian/mobile-apps-api/pull/2760
    branches:
      - main # Optimal for GHA workflow caching - see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  workflow_dispatch:

jobs:
  build_pandoc_converter:
    name: Build pandoc-converter
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build release.nix

      - run: nix-store --export $(nix-store -qR ./result) > pandoc-converter.closure

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: "cdk/.nvmrc"
          cache: npm
          cache-dependency-path: cdk/package-lock.json

        # Setup & RUN CDK
      - name: Run CDK
        working-directory: cdk
        run: |
          npm ci
          npm run lint
          npm run test
          npm run synth

      - uses: guardian/actions-riff-raff@v4
        with:
          app: pandoc-converter
          projectName: Content Platforms::pandoc-converter
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out/PandocConverter-euwest-1-CODE.template.json
              - cdk/cdk.out/PandocConverter-euwest-1-PROD.template.json
            pandoc-converter:
              - pandoc-converter.closure

  lint_pandoc_converter:
    name: Lint pandoc-converter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify nix file is up to date with cabal file
        run: |
          nix-shell -p cabal2nix --run "cabal2nix . > pandoc-converter-check.nix"
          diff pandoc-converter.nix pandoc-converter-check.nix
