name: pandoc-converter build

on:
  pull_request: {}
  push: # Do not rely on `push` for PR CI - see https://github.com/guardian/mobile-apps-api/pull/2760
    branches:
      - main # Optimal for GHA workflow caching - see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  workflow_dispatch:

jobs:
  build_pandoc_converter:
    name: Build pandoc-converter
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell -p cabal2nix --run "cabal2nix . > pandoc-converter.nix"

      - run: nix-build release.nix

      - run: ./result/bin/PandocConverter < test.md

      - run: nix-store --export $(nix-store -qR ./result) > pandoc-converter.closure

      - uses: guardian/actions-riff-raff@v4
        with:
          app: pandoc-converter
          projectName: Content Platforms::pandoc-converter
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            pandoc-converter:
              - pandoc-converter.closure
